[package]
name = "template"
version = "0.1.0"
edition = "2024"
crate-type = ["cdylib"]

[lib]
name = "template"
crate-type = ["cdylib"]

[dependencies]
serde_json = "1.0.140"
serde = { version = "1.0.219", features = ["derive"]}
