[package]
name = "files"
version = "0.1.0"
edition = "2024"
crate-type = ["cdylib"]

[lib]
name = "files"
crate-type = ["cdylib"]

[dependencies]
arboard = "3.6.0"
nocast_plugincore = { git = "https://github.com/roger-padrell/nocast_plugincore" }
rayon = "1.10.0"
walkdir = "2.5.0"
