name = "files"
version = "0.0.1"
author = "roger"
license = "MIT"
source = "."

[[actions]]
name = "search_files"
expression = "(.*)"
function = "search_files"
autorun = true

[[actions]]
name = "copy_path"
expression = "a^"
function = "copy_path"
autorun = false
