[package]
name = "sample"
version = "0.1.0"
edition = "2024"
crate-type = ["cdylib"]

[lib]
name = "sample"
crate-type = ["cdylib"]

[dependencies]
nocast_plugincore = { git = "https://github.com/roger-padrell/nocast_plugincore" }
