[package]
name = "linuxlauncher"
version = "0.1.0"
edition = "2024"
crate-type = ["cdylib"]

[lib]
name = "linuxlauncher"
crate-type = ["cdylib"]

[dependencies]
dirs = "6.0.0"
nocast_plugincore = { git = "https://github.com/roger-padrell/nocast_plugincore" }
