name = "linuxlauncher"
version = "0.0.1"
author = "roger"
license = "MIT"
source = "."

[[actions]]
name = "searchapp"
expression = "(.*)"
function = "searchapp"
autorun = true

[[actions]]
name = "openapp"
expression = "a^"
function = "openapp"
autorun = false

