[package]
name = "calculator"
version = "0.1.0"
edition = "2024"
crate-type = ["cdylib"]

[lib]
name = "calculator"
crate-type = ["cdylib"]

[dependencies]
arboard = "3.6.0"
meval = "0.2.0"
nocast_plugincore = { git = "https://github.com/roger-padrell/nocast_plugincore" }
