name = "calculator"
version = "0.0.1"
author = "roger"
license = "MIT"
source = "."

[[actions]]
name = "operation"
expression = "^\\s*-?\\d+(?:\\.\\d+)?(?:\\s*(?:\\*\\*|[+\\-*/])\\s*-?\\d+(?:\\.\\d+)?)*\\s*$"
function = "operation"
autorun = true

[[actions]]
name = "copy_result"
expression = "a^"
function = "copy_result"
autorun = false

