name = "calculator"
version = "0.0.1"
author = "roger"
license = "MIT"
source = "."

[[actions]]
name = "operation"
expression = "(.*)"  #"^\\s*-?\\d+(?:\\.\\d+)?(?:\\s*(?:\\*\\*|[+\\-*/])\\s*-?\\d+(?:\\.\\d+)?)*\\s*$"
function = "operation"
autorun = true

[[actions]]
name = "lenght_convert"
expression = "\\b(\\d+(\\.\\d+)?)(\\s*)(cm|centimeters?|m|meters?|mm|millimeters?|km|kilometers?|in|inches|ft|feet|yd|yards?|mi|miles?)\\s*(in|to|→)\\s*(cm|centimeters?|m|meters?|mm|millimeters?|km|kilometers?|in|inches|ft|feet|yd|yards?|mi|miles?)\\b"
function = "lenght_convert"
autorun = true

[[actions]]
name = "copy_result"
expression = "a^"
function = "copy_result"
autorun = false

